In [1]:
import pandas as pd
data_set = pd.read_csv('DiseaseAndSymptoms.csv')

In [2]:
symptoms_dataframe = data_set.drop('Disease',axis=1)
symptoms_dataframe = symptoms_dataframe.fillna('None')

first_list = [ ]
for row_index in symptoms_dataframe.index:
  for column_name in symptoms_dataframe.columns:
    cell_value = symptoms_dataframe.loc[row_index,column_name]
    cell_value = cell_value.strip()
    if(cell_value != 'None'):
      first_list.append((row_index,column_name,cell_value))

In [3]:
stacked_dataframe = pd.DataFrame(first_list)
stacked_dataframe[3] = 1
display(stacked_dataframe)


#This is encoding with 1
indra_chowk = pd.pivot_table(data=stacked_dataframe,index=0,columns=2,values=3)
#This is encoding with 0
indra_chowk = indra_chowk.fillna('0')
indra_chowk = indra_chowk.astype(int)
display(indra_chowk)

          0          1                     2  3
0         0  Symptom_1               itching  1
1         0  Symptom_2             skin_rash  1
2         0  Symptom_3  nodal_skin_eruptions  1
3         0  Symptom_4   dischromic _patches  1
4         1  Symptom_1             skin_rash  1
...     ...        ...                   ... ..
36643  4919  Symptom_1             skin_rash  1
36644  4919  Symptom_2            high_fever  1
36645  4919  Symptom_3               blister  1
36646  4919  Symptom_4  red_sore_around_nose  1
36647  4919  Symptom_5     yellow_crust_ooze  1

[36648 rows x 4 columns]

2,abdominal_pain,abnormal_menstruation,acidity,acute_liver_failure,altered_sensorium,anxiety,back_pain,belly_pain,blackheads,bladder_discomfort,...,vomiting,watering_from_eyes,weakness_in_limbs,weakness_of_one_body_side,weight_gain,weight_loss,yellow_crust_ooze,yellow_urine,yellowing_of_eyes,yellowish_skin
0,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4916,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4917,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4918,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4919,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [4]:
disease = data_set['Disease']
from sklearn.preprocessing import LabelEncoder
disease_encoder = LabelEncoder()
encoding_disease = disease_encoder.fit_transform(disease)
encoded_disease = pd.Series(encoding_disease)

import warnings
warnings.filterwarnings('ignore')
indra_chowk.insert(loc=0,column='Disease',value=encoded_disease)

In [5]:
import pandas as pd
original_testing_dataset = pd.read_csv('Mendeley.csv')
print(original_testing_dataset.iloc[[0]])

         diseases  anxiety and nervousness  depression  shortness of breath  \
0  panic disorder                        1           0                    1

   depressive or psychotic symptoms  sharp chest pain  dizziness  insomnia  \
0                                 1                 0          0         0

   abnormal involuntary movements  chest tightness  ...  \
0                               0                1  ...

   stuttering or stammering  problems with orgasm  nose deformity  \
0                         0                     0               0

   lump over jaw  sore in nose  hip weakness  back swelling  \
0              0             0             0              0

   ankle stiffness or tightness  ankle weakness  neck weakness
0                             0               0              0

[1 rows x 378 columns]

In [6]:
renaming_mendeley = {
    'chickenpox' : 'chicken pox',
    'osteoarthritis' : 'osteoarthristis',
    'asthma' : 'bronchial asthma',
    'gastroesophageal reflux disease (gerd)' : 'gerd',
    'hemorrhoids' : 'dimorphic hemmorhoids(piles)'
}

In [7]:
original_testing_dataset['diseases'] = original_testing_dataset['diseases'].replace(renaming_mendeley)
heram_list = list(original_testing_dataset['diseases'])

In [8]:
second_list = ['chicken pox','osteoarthristis','bronchial asthma','gerd','dimorphic hemmorhoids(piles)']
for c in second_list:
    if(c in heram_list):
        print(c)

chicken pox
osteoarthristis
bronchial asthma
gerd
dimorphic hemmorhoids(piles)

In [9]:
original_testing_dataset['diseases'] = original_testing_dataset['diseases'].str.strip().str.lower()

In [10]:
kaggle_diseases = [c.lower().strip() for c in disease_encoder.classes_]

In [11]:
new_mendeley = original_testing_dataset[original_testing_dataset['diseases'].isin(kaggle_diseases)]
# This dataset now has the diseases and its rows which are in Kaggle and Mendeley.

In [12]:
occurences = new_mendeley['diseases'].value_counts()
a = new_mendeley['diseases'].unique()
print(len(a))
print(occurences)

21
diseases
hypoglycemia                    1215
pneumonia                       1212
psoriasis                        912
urinary tract infection          910
drug reaction                    909
dimorphic hemmorhoids(piles)     908
heart attack                     907
allergy                          905
common cold                      905
bronchial asthma                 904
osteoarthristis                  896
impetigo                         683
acne                             496
gerd                             448
migraine                         221
varicose veins                   113
chicken pox                      104
hypothyroidism                    74
tuberculosis                      23
malaria                           15
diabetes                           1
Name: count, dtype: int64

In [13]:
print(occurences.index)
print(occurences.values)

Index(['hypoglycemia', 'pneumonia', 'psoriasis', 'urinary tract infection',
       'drug reaction', 'dimorphic hemmorhoids(piles)', 'heart attack',
       'allergy', 'common cold', 'bronchial asthma', 'osteoarthristis',
       'impetigo', 'acne', 'gerd', 'migraine', 'varicose veins', 'chicken pox',
       'hypothyroidism', 'tuberculosis', 'malaria', 'diabetes'],
      dtype='str', name='diseases')
[1215 1212  912  910  909  908  907  905  905  904  896  683  496  448
  221  113  104   74   23   15    1]

In [14]:
print(occurences.values[1])
print(occurences.index[1])

1212
pneumonia

In [15]:
keep = [ ]
for i in range(0,20):
    if(occurences.values[i] > 100):
        keep.append(occurences.index[i])
print(keep)

['hypoglycemia', 'pneumonia', 'psoriasis', 'urinary tract infection', 'drug reaction', 'dimorphic hemmorhoids(piles)', 'heart attack', 'allergy', 'common cold', 'bronchial asthma', 'osteoarthristis', 'impetigo', 'acne', 'gerd', 'migraine', 'varicose veins', 'chicken pox']

In [16]:
new_mendeley = new_mendeley[new_mendeley['diseases'].isin(keep)]
print(new_mendeley['diseases'].unique())

<ArrowStringArray>
[            'bronchial asthma',                         'gerd',
                 'hypoglycemia',                      'allergy',
               'varicose veins',                'drug reaction',
              'osteoarthristis',                    'pneumonia',
                 'heart attack',                    'psoriasis',
                  'chicken pox',                  'common cold',
                         'acne',                     'impetigo',
                     'migraine', 'dimorphic hemmorhoids(piles)',
      'urinary tract infection']
Length: 17, dtype: str

In [17]:
new_mendeley = pd.DataFrame(new_mendeley)

In [18]:
mendeley_symptoms_list = list(new_mendeley.columns)
mendeley_symptoms_list.remove('diseases')
print(len(mendeley_symptoms_list))

377

In [19]:
kaggle_symptoms_list = list(indra_chowk.columns)
kaggle_symptoms_list.remove('Disease')
print(len(kaggle_symptoms_list))

131

In [20]:
kaggle_symptoms_list = [k_symp.replace('_',' ') for k_symp in kaggle_symptoms_list]

In [21]:
just = [ ]
for m_symp in mendeley_symptoms_list:
    if(m_symp in kaggle_symptoms_list):
        just.append(m_symp)
print(just)
print(len(just))

['depression', 'dizziness', 'palpitations', 'cough', 'vomiting', 'headache', 'nausea', 'back pain', 'neck pain', 'restlessness', 'knee pain', 'weight gain', 'muscle pain', 'joint pain', 'chills', 'fatigue', 'constipation', 'sweating', 'skin rash', 'throat irritation', 'polyuria', 'muscle weakness']
22

In [22]:
!pip install google-genai

Requirement already satisfied: google-genai in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (2.33.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from google-genai) (4.12.1)
Requirement already satisfied: google-auth<3.0.0,>=2.56.0 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.62.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.12.5 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from google-genai) (2.13.4)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from google-genai) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<18.0,>=13.0.0 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from google-genai) (16.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from google-genai) (4.16.0)
Requirement already satisfied: distro<2,>=1.7.0 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.18)
Requirement already satisfied: pyasn1-modules>=0.2.1 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=41.0.5 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (49.0.0)
Requirement already satisfied: certifi in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.6.17)
Requirement already satisfied: httpcore==1.* in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.7.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from cryptography>=41.0.5->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.1.0)
Requirement already satisfied: pycparser in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from cffi>=2.0.0->cryptography>=41.0.5->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in C:\Users\Abhigya Rai\Downloads\Anaconda\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.6.4)

In [23]:
from google import genai
import os

In [24]:
!pip install -q python-dotenv

In [25]:
from dotenv import load_dotenv

In [26]:
load_dotenv(r"C:\Users\Abhigya Rai\Downloads\DiseaseDiagnosisApp\API Key.env",override=True)

True

In [27]:
gemini_api_key = os.environ["API_saacho"]
print(gemini_api_key[-4:])

QBBg

In [28]:
client = genai.Client(api_key = gemini_api_key)

In [33]:
import json
kaggle_symptoms_to_match = [k for k in kaggle_symptoms_list if k not in just]
prompt = f"""Match each symptoms in LIST A with the closest equivalent that is in LIST B. 
Don't try to forecefully match the symptoms in LIST A with LIST B.
Only match if they are similar or convey the same meaning.
If no equivalent exists, just use null.
During matching, use the exact words that are in LIST B. 
Return the answer in JSON format: {{"<LIST A symptom>" : "<LIST B symptom or null>\n"}}

LIST A : {kaggle_symptoms_to_match}
LIST B : {mendeley_symptoms_list}"""

try:
    response = client.models.generate_content(
        model = "gemini-3.5-flash",
        contents = prompt,
        config = {"response_mime_type" : "application/json"}
    )
    gemini_map = json.loads(response.text)
    print(gemini_map)
except Exception as e:
    print(f"Sorry, there's an error: {e}")

Sorry, there's an error: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}