<a href="https://colab.research.google.com/github/ABHIGYA-RAI/Disease-diagnostic-support-system/blob/main/Symptom%26Disease_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data_set = pd.read_csv('/content/DiseaseAndSymptoms.csv')

In [3]:
symbi_predict = pd.read_csv('/content/symbipredict_2022.csv')
print(symbi_predict)

      itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0
1           0          1                     1                    0
2           1          0                     1                    0
3           1          1                     0                    0
4           1          1                     1                    0
...       ...        ...                   ...                  ...
4956        0          0                     0                    0
4957        0          1                     0                    0
4958        0          0                     0                    0
4959        0          1                     0                    0
4960        0          1                     0                    0

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0
1             0       0           0             0        0                 0
2             0       0           0             0        0                 0
3             0       0           0             0        0                 0
4             0       0           0             0        0                 0
...         ...     ...         ...           ...      ...               ...
4956          0       0           0             0        0                 0
4957          0       0           0             0        0                 0
4958          0       0           0             0        0                 0
4959          0       0           1             0        0                 0
4960          0       0           0             0        0                 0

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...           0         0             0                    0
1     ...           0         0             0                    0
2     ...           0         0             0                    0
3     ...           0         0             0                    0
4     ...           0         0             0                    0
...   ...         ...       ...           ...                  ...
4956  ...           0         0             0                    0
4957  ...           1         1             0                    0
4958  ...           0         0             0                    0
4959  ...           0         0             1                    1
4960  ...           0         0             0                    0

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                        0                   0        0                     0
1                        0                   0        0                     0
2                        0                   0        0                     0
3                        0                   0        0                     0
4                        0                   0        0                     0
...                    ...                 ...      ...                   ...
4956                     0                   0        0                     0
4957                     0                   0        0                     0
4958                     0                   0        0                     0
4959                     1                   1        0                     0
4960                     0                   0        1                     1

      yellow_crust_ooze                prognosis
0                     0         Fungal Infection
1                     0         Fungal Infection
2                     0         Fungal Infection
3                     0         Fungal Infection
4                     0         Fungal Infection
...                 ...                      ...
4956                  0                  Vertigo
4957                  0                     Acne
4958                  0  Urinary Tract Infection
4959                  0                Psoriasis
4960                  1                 Impetigo

[4961 rows x 132 columns]

In [4]:
symptoms_dataframe = data_set.drop('Disease',axis=1)
symptoms_dataframe = symptoms_dataframe.fillna('None')

In [5]:
first_list = [ ]
for row_index in symptoms_dataframe.index:
  for column_name in symptoms_dataframe.columns:
    cell_value = symptoms_dataframe.loc[row_index,column_name]
    cell_value = cell_value.strip()
    if(cell_value != 'None'):
      first_list.append((row_index,column_name,cell_value))
print(first_list)

[(0, 'Symptom_1', 'itching'), (0, 'Symptom_2', 'skin_rash'), (0, 'Symptom_3', 'nodal_skin_eruptions'), (0, 'Symptom_4', 'dischromic _patches'), (1, 'Symptom_1', 'skin_rash'), (1, 'Symptom_2', 'nodal_skin_eruptions'), (1, 'Symptom_3', 'dischromic _patches'), (2, 'Symptom_1', 'itching'), (2, 'Symptom_2', 'nodal_skin_eruptions'), (2, 'Symptom_3', 'dischromic _patches'), (3, 'Symptom_1', 'itching'), (3, 'Symptom_2', 'skin_rash'), (3, 'Symptom_3', 'dischromic _patches'), (4, 'Symptom_1', 'itching'), (4, 'Symptom_2', 'skin_rash'), (4, 'Symptom_3', 'nodal_skin_eruptions'), (5, 'Symptom_1', 'skin_rash'), (5, 'Symptom_2', 'nodal_skin_eruptions'), (5, 'Symptom_3', 'dischromic _patches'), (6, 'Symptom_1', 'itching'), (6, 'Symptom_2', 'nodal_skin_eruptions'), (6, 'Symptom_3', 'dischromic _patches'), (7, 'Symptom_1', 'itching'), (7, 'Symptom_2', 'skin_rash'), (7, 'Symptom_3', 'dischromic _patches'), (8, 'Symptom_1', 'itching'), (8, 'Symptom_2', 'skin_rash'), (8, 'Symptom_3', 'nodal_skin_eruptions'), (9, 'Symptom_1', 'itching'), (9, 'Symptom_2', 'skin_rash'), (9, 'Symptom_3', 'nodal_skin_eruptions'), (9, 'Symptom_4', 'dischromic _patches'), (10, 'Symptom_1', 'continuous_sneezing'), (10, 'Symptom_2', 'shivering'), (10, 'Symptom_3', 'chills'), (10, 'Symptom_4', 'watering_from_eyes'), (11, 'Symptom_1', 'shivering'), (11, 'Symptom_2', 'chills'), (11, 'Symptom_3', 'watering_from_eyes'), (12, 'Symptom_1', 'continuous_sneezing'), (12, 'Symptom_2', 'chills'), (12, 'Symptom_3', 'watering_from_eyes'), (13, 'Symptom_1', 'continuous_sneezing'), (13, 'Symptom_2', 'shivering'), (13, 'Symptom_3', 'watering_from_eyes'), (14, 'Symptom_1', 'continuous_sneezing'), (14, 'Symptom_2', 'shivering'), (14, 'Symptom_3', 'chills'), (15, 'Symptom_1', 'shivering'), (15, 'Symptom_2', 'chills'), (15, 'Symptom_3', 'watering_from_eyes'), (16, 'Symptom_1', 'continuous_sneezing'), (16, 'Symptom_2', 'chills'), (16, 'Symptom_3', 'watering_from_eyes'), (17, 'Symptom_1', 'continuous_sneezing'), (17, 'Symptom_2', 'shivering'), (17, 'Symptom_3', 'watering_from_eyes'), (18, 'Symptom_1', 'continuous_sneezing'), (18, 'Symptom_2', 'shivering'), (18, 'Symptom_3', 'chills'), (19, 'Symptom_1', 'continuous_sneezing'), (19, 'Symptom_2', 'shivering'), (19, 'Symptom_3', 'chills'), (19, 'Symptom_4', 'watering_from_eyes'), (20, 'Symptom_1', 'stomach_pain'), (20, 'Symptom_2', 'acidity'), (20, 'Symptom_3', 'ulcers_on_tongue'), (20, 'Symptom_4', 'vomiting'), (20, 'Symptom_5', 'cough'), (20, 'Symptom_6', 'chest_pain'), (21, 'Symptom_1', 'stomach_pain'), (21, 'Symptom_2', 'ulcers_on_tongue'), (21, 'Symptom_3', 'vomiting'), (21, 'Symptom_4', 'cough'), (21, 'Symptom_5', 'chest_pain'), (22, 'Symptom_1', 'stomach_pain'), (22, 'Symptom_2', 'acidity'), (22, 'Symptom_3', 'vomiting'), (22, 'Symptom_4', 'cough'), (22, 'Symptom_5', 'chest_pain'), (23, 'Symptom_1', 'stomach_pain'), (23, 'Symptom_2', 'acidity'), (23, 'Symptom_3', 'ulcers_on_tongue'), (23, 'Symptom_4', 'cough'), (23, 'Symptom_5', 'chest_pain'), (24, 'Symptom_1', 'stomach_pain'), (24, 'Symptom_2', 'acidity'), (24, 'Symptom_3', 'ulcers_on_tongue'), (24, 'Symptom_4', 'vomiting'), (24, 'Symptom_5', 'chest_pain'), (25, 'Symptom_1', 'stomach_pain'), (25, 'Symptom_2', 'acidity'), (25, 'Symptom_3', 'ulcers_on_tongue'), (25, 'Symptom_4', 'vomiting'), (25, 'Symptom_5', 'cough'), (26, 'Symptom_1', 'acidity'), (26, 'Symptom_2', 'ulcers_on_tongue'), (26, 'Symptom_3', 'vomiting'), (26, 'Symptom_4', 'cough'), (26, 'Symptom_5', 'chest_pain'), (27, 'Symptom_1', 'stomach_pain'), (27, 'Symptom_2', 'ulcers_on_tongue'), (27, 'Symptom_3', 'vomiting'), (27, 'Symptom_4', 'cough'), (27, 'Symptom_5', 'chest_pain'), (28, 'Symptom_1', 'stomach_pain'), (28, 'Symptom_2', 'acidity'), (28, 'Symptom_3', 'vomiting'), (28, 'Symptom_4', 'cough'), (28, 'Symptom_5', 'chest_pain'), (29, 'Symptom_1', 'stomach_pain'), (29, 'Symptom_2', 'acidity'), (29, 'Symptom_3', 'ulcers_on_tongue'), (29, 'Symptom_4', 'cough'), (29, 'Symptom_5', 'chest_pain'), (30, 'Symptom_1', 'itching'), (30, 'Symptom_2', 'vomiting'), (30, 'Symptom_3', 'yellowish_skin'), (30, 'Symptom_4', 'nausea'), (30, 'Symptom_5', 'loss_of_appetite'), (30, 'Symptom_6', 'abdominal_pain'), (30, 'Symptom_7', 'yellowing_of_eyes'), (31, 'Symptom_1', 'vomiting'), (31, 'Symptom_2', 'yellowish_skin'), (31, 'Symptom_3', 'nausea'), (31, 'Symptom_4', 'loss_of_appetite'), (31, 'Symptom_5', 'abdominal_pain'), (31, 'Symptom_6', 'yellowing_of_eyes'), (32, 'Symptom_1', 'itching'), (32, 'Symptom_2', 'yellowish_skin'), (32, 'Symptom_3', 'nausea'), (32, 'Symptom_4', 'loss_of_appetite'), (32, 'Symptom_5', 'abdominal_pain'), (32, 'Symptom_6', 'yellowing_of_eyes'), (33, 'Symptom_1', 'itching'), (33, 'Symptom_2', 'vomiting'), (33, 'Symptom_3', 'nausea'), (33, 'Symptom_4', 'loss_of_appetite'), (33, 'Symptom_5', 'abdominal_pain'), (33, 'Symptom_6', 'yellowing_of_eyes'), (34, 'Symptom_1', 'itching'), (34, 'Symptom_2', 'vomiting'), (34, 'Symptom_3', 'yellowish_skin'), (34, 'Symptom_4', 'loss_of_appetite'), (34, 'Symptom_5', 'abdominal_pain'), (34, 'Symptom_6', 'yellowing_of_eyes'), (35, 'Symptom_1', 'itching'), (35, 'Symptom_2', 'vomiting'), (35, 'Symptom_3', 'yellowish_skin'), (35, 'Symptom_4', 'nausea'), (35, 'Symptom_5', 'abdominal_pain'), (35, 'Symptom_6', 'yellowing_of_eyes'), (36, 'Symptom_1', 'itching'), (36, 'Symptom_2', 'vomiting'), (36, 'Symptom_3', 'yellowish_skin'), (36, 'Symptom_4', 'nausea'), (36, 'Symptom_5', 'loss_of_appetite'), (36, 'Symptom_6', 'yellowing_of_eyes'), (37, 'Symptom_1', 'itching'), (37, 'Symptom_2', 'vomiting'), (37, 'Symptom_3', 'yellowish_skin'), (37, 'Symptom_4', 'nausea'), (37, 'Symptom_5', 'loss_of_appetite'), (37, 'Symptom_6', 'abdominal_pain'), (38, 'Symptom_1', 'itching'), (38, 'Symptom_2', 'vomiting'), (38, 'Symptom_3', 'yellowish_skin'), (38, 'Symptom_4', 'nausea'), (38, 'Symptom_5', 'loss_of_appetite'), (38, 'Symptom_6', 'abdominal_pain'), (38, 'Symptom_7', 'yellowing_of_eyes'), (39, 'Symptom_1', 'itching'), (39, 'Symptom_2', 'vomiting'), (39, 'Symptom_3', 'yellowish_skin'), (39, 'Symptom_4', 'nausea'), (39, 'Symptom_5', 'loss_of_appetite'), (39, 'Symptom_6', 'abdominal_pain'), (39, 'Symptom_7', 'yellowing_of_eyes'), (40, 'Symptom_1', 'itching'), (40, 'Symptom_2', 'skin_rash'), (40, 'Symptom_3', 'stomach_pain'), (40, 'Symptom_4', 'burning_micturition'), (40, 'Symptom_5', 'spotting_ urination'), (41, 'Symptom_1', 'itching'), (41, 'Symptom_2', 'stomach_pain'), (41, 'Symptom_3', 'burning_micturition'), (41, 'Symptom_4', 'spotting_ urination'), (42, 'Symptom_1', 'itching'), (42, 'Symptom_2', 'skin_rash'), (42, 'Symptom_3', 'burning_micturition'), (42, 'Symptom_4', 'spotting_ urination'), (43, 'Symptom_1', 'itching'), (43, 'Symptom_2', 'skin_rash'), (43, 'Symptom_3', 'stomach_pain'), (43, 'Symptom_4', 'spotting_ urination'), (44, 'Symptom_1', 'itching'), (44, 'Symptom_2', 'skin_rash'), (44, 'Symptom_3', 'stomach_pain'), (44, 'Symptom_4', 'burning_micturition'), (45, 'Symptom_1', 'skin_rash'), (45, 'Symptom_2', 'stomach_pain'), (45, 'Symptom_3', 'burning_micturition'), (45, 'Symptom_4', 'spotting_ urination'), (46, 'Symptom_1', 'itching'), (46, 'Symptom_2', 'stomach_pain'), (46, 'Symptom_3', 'burning_micturition'), (46, 'Symptom_4', 'spotting_ urination'), (47, 'Symptom_1', 'itching'), (47, 'Symptom_2', 'skin_rash'), (47, 'Symptom_3', 'burning_micturition'), (47, 'Symptom_4', 'spotting_ urination'), (48, 'Symptom_1', 'itching'), (48, 'Symptom_2', 'skin_rash'), (48, 'Symptom_3', 'stomach_pain'), (48, 'Symptom_4', 'spotting_ urination'), (49, 'Symptom_1', 'itching'), (49, 'Symptom_2', 'skin_rash'), (49, 'Symptom_3', 'stomach_pain'), (49, 'Symptom_4', 'burning_micturition'), (50, 'Symptom_1', 'vomiting'), (50, 'Symptom_2', 'loss_of_appetite'), (50, 'Symptom_3', 'abdominal_pain'), (50, 'Symptom_4', 'passage_of_gases'), (50, 'Symptom_5', 'internal_itching'), (51, 'Symptom_1', 'vomiting'), (51, 'Symptom_2', 'indigestion'), (51, 'Symptom_3', 'abdominal_pain'), (51, 'Symptom_4', 'passage_of_gases'), (51, 'Symptom_5', 'internal_itching'), (52, 'Symptom_1', 'indigestion'), (52, 'Symptom_2', 'loss_of_appetite'), (52, 'Symptom_3', 'abdominal_pain'), (52, 'Symptom_4', 'passage_of_gases'), (52, 'Symptom_5', 'internal_itching'), (53, 'Symptom_1', 'vomiting'), (53, 'Symptom_2', 'loss_of_appetite'), (53, 'Symptom_3', 'abdominal_pain'), (53, 'Symptom_4', 'passage_of_gases'), (53, 'Symptom_5', 'internal_itching'), (54, 'Symptom_1', 'vomiting'), (54, 'Symptom_2', 'indigestion'), (54, 'Symptom_3', 'abdominal_pain'), (54, 'Symptom_4', 'passage_of_gases'), (54, 'Symptom_5', 'internal_itching'), (55, 'Symptom_1', 'vomiting'), (55, 'Symptom_2', 'indigestion'), (55, 'Symptom_3', 'loss_of_appetite'), (55, 'Symptom_4', 'passage_of_gases'), (55, 'Symptom_5', 'internal_itching'), (56, 'Symptom_1', 'vomiting'), (56, 'Symptom_2', 'indigestion'), (56, 'Symptom_3', 'loss_of_appetite'), (56, 'Symptom_4', 'abdominal_pain'), (56, 'Symptom_5', 'internal_itching'), (57, 'Symptom_1', 'vomiting'), (57, 'Symptom_2', 'indigestion'), (57, 'Symptom_3', 'loss_of_appetite'), (57, 'Symptom_4', 'abdominal_pain'), (57, 'Symptom_5', 'passage_of_gases'), (58, 'Symptom_1', 'vomiting'), (58, 'Symptom_2', 'indigestion'), (58, 'Symptom_3', 'loss_of_appetite'), (58, 'Symptom_4', 'abdominal_pain'), (58, 'Symptom_5', 'passage_of_gases'), (58, 'Symptom_6', 'internal_itching'), (59, 'Symptom_1', 'vomiting'), (59, 'Symptom_2', 'indigestion'), (59, 'Symptom_3', 'loss_of_appetite'), (59, 'Symptom_4', 'abdominal_pain'), (59, 'Symptom_5', 'passage_of_gases'), (59, 'Symptom_6', 'internal_itching'), (60, 'Symptom_1', 'muscle_wasting'), (60, 'Symptom_2', 'patches_in_throat'), (60, 'Symptom_3', 'high_fever'), (60, 'Symptom_4', 'extra_marital_contacts'), (61, 'Symptom_1', 'patches_in_throat'), (61, 'Symptom_2', 'high_fever'), (61, 'Symptom_3', 'extra_marital_contacts'), (62, 'Symptom_1', 'muscle_wasting'), (62, 'Symptom_2', 'high_fever'), (62, 'Symptom_3', 'extra_marital_contacts'), (63, 'Symptom_1', 'muscle_wasting'), (63, 'Symptom_2', 'patches_in_throat'), (63, 'Symptom_3', 'extra_marital_contacts'), (64, 'Symptom_1', 'muscle_wasting'), (64, 'Symptom_2', 'patches_in_throat'), (64, 'Symptom_3', 'high_fever'), (65, 'Symptom_1', 'muscle_wasting'), (65, 'Symptom_2', 'patches_in_throat'), (65, 'Symptom_3', 'high_fever'), (65, 'Symptom_4', 'extra_marital_contacts'), (66, 'Symptom_1', 'muscle_wasting'), (66, 'Symptom_2', 'patches_in_throat'), (66, 'Symptom_3', 'high_fever'), (66, 'Symptom_4', 'extra_marital_contacts'), (67, 'Symptom_1', 'patches_in_throat'), (67, 'Symptom_2', 'high_fever'), (67, 'Symptom_3', 'extra_marital_contacts'), (68, 'Symptom_1', 'muscle_wasting'), (68, 'Symptom_2', 'high_fever'), (68, 'Symptom_3', 'extra_marital_contacts'), (69, 'Symptom_1', 'muscle_wasting'), (69, 'Symptom_2', 'patches_in_throat'), (69, 'Symptom_3', 'high_fever'), (70, 'Symptom_1', 'fatigue'), (70, 'Symptom_2', 'weight_loss'), (70, 'Symptom_3', 'restlessness'), (70, 'Symptom_4', 'lethargy'), (70, 'Symptom_5', 'irregular_sugar_level'), (70, 'Symptom_6', 'blurred_and_distorted_vision'), (70, 'Symptom_7', 'obesity'), (70, 'Symptom_8', 'excessive_hunger'), (70, 'Symptom_9', 'increased_appetite'), (70, 'Symptom_10', 'polyuria'), (71, 'Symptom_1', 'fatigue'), (71, 'Symptom_2', 'weight_loss'), (71, 'Symptom_3', 'restlessness'), (71, 'Symptom_4', 'lethargy'), (71, 'Symptom_5', 'irregular_sugar_level'), (71, 'Symptom_6', 'blurred_and_distorted_vision'), (71, 'Symptom_7', 'obesity'), (71, 'Symptom_8', 'excessive_hunger'), (71, 'Symptom_9', 'increased_appetite'), (71, 'Symptom_10', 'polyuria'), (72, 'Symptom_1', 'weight_loss'), (72, 'Symptom_2', 'restlessness'), (72, 'Symptom_3', 'lethargy'), (72, 'Symptom_4', 'irregular_sugar_level'), (72, 'Symptom_5', 'blurred_and_distorted_vision'), (72, 'Symptom_6', 'obesity'), (72, 'Symptom_7', 'excessive_hunger'), (72, 'Symptom_8', 'increased_appetite'), (72, 'Symptom_9', 'polyuria'), (73, 'Symptom_1', 'fatigue'), (73, 'Symptom_2', 'restlessness'), (73, 'Symptom_3', 'lethargy'), (73, 'Symptom_4', 'irregular_sugar_level'), (73, 'Symptom_5', 'blurred_and_distorted_vision'), (73, 'Symptom_6', 'obesity'), (73, 'Symptom_7', 'excessive_hunger'), (73, 'Symptom_8', 'increased_appetite'), (73, 'Symptom_9', 'polyuria'), (74, 'Symptom_1', 'fatigue'), (74, 'Symptom_2', 'weight_loss'), (74, 'Symptom_3', 'lethargy'), (74, 'Symptom_4', 'irregular_sugar_level'), (74, 'Symptom_5', 'blurred_and_distorted_vision'), (74, 'Symptom_6', 'obesity'), (74, 'Symptom_7', 'excessive_hunger'), (74, 'Symptom_8', 'increased_appetite'), (74, 'Symptom_9', 'polyuria'), (75, 'Symptom_1', 'fatigue'), (75, 'Symptom_2', 'weight_loss'), (75, 'Symptom_3', 'restlessness'), (75, 'Symptom_4', 'irregular_sugar_level'), (75, 'Symptom_5', 'blurred_and_distorted_vision'), (75, 'Symptom_6', 'obesity'), (75, 'Symptom_7', 'excessive_hunger'), (75, 'Symptom_8', 'increased_appetite'), (75, 'Symptom_9', 'polyuria'), (76, 'Symptom_1', 'fatigue'), (76, 'Symptom_2', 'weight_loss'), (76, 'Symptom_3', 'restlessness'), (76, 'Symptom_4', 'lethargy'), (76, 'Symptom_5', 'blurred_and_distorted_vision'), (76, 'Symptom_6', 'obesity'), (76, 'Symptom_7', 'excessive_hunger'), (76, 'Symptom_8', 'increased_appetite'), (76, 'Symptom_9', 'polyuria'), (77, 'Symptom_1', 'fatigue'), (77, 'Symptom_2', 'weight_loss'), (77, 'Symptom_3', 'restlessness'), (77, 'Symptom_4', 'lethargy'), (77, 'Symptom_5', 'irregular_sugar_level'), (77, 'Symptom_6', 'obesity'), (77, 'Symptom_7', 'excessive_hunger'), (77, 'Symptom_8', 'increased_appetite'), (77, 'Symptom_9', 'polyuria'), (78, 'Symptom_1', 'fatigue'), (78, 'Symptom_2', 'weight_loss'), (78, 'Symptom_3', 'restlessness'), (78, 'Symptom_4', 'lethargy'), (78, 'Symptom_5', 'irregular_sugar_level'), (78, 'Symptom_6', 'blurred_and_distorted_vision'), (78, 'Symptom_7', 'excessive_hunger'), (78, 'Symptom_8', 'increased_appetite'), (78, 'Symptom_9', 'polyuria'), (79, 'Symptom_1', 'fatigue'), (79, 'Symptom_2', 'weight_loss'), (79, 'Symptom_3', 'restlessness'), (79, 'Symptom_4', 'lethargy'), (79, 'Symptom_5', 'irregular_sugar_level'), (79, 'Symptom_6', 'blurred_and_distorted_vision'), (79, 'Symptom_7', 'obesity'), (79, 'Symptom_8', 'increased_appetite'), (79, 'Symptom_9', 'polyuria'), (80, 'Symptom_1', 'vomiting'), (80, 'Symptom_2', 'sunken_eyes'), (80, 'Symptom_3', 'dehydration'), (80, 'Symptom_4', 'diarrhoea'), (81, 'Symptom_1', 'vomiting'), (81, 'Symptom_2', 'sunken_eyes'), (81, 'Symptom_3', 'dehydration'), (81, 'Symptom_4', 'diarrhoea'), (82, 'Symptom_1', 'sunken_eyes'), (82, 'Symptom_2', 'dehydration'), (82, 'Symptom_3', 'diarrhoea'), (83, 'Symptom_1', 'vomiting'), (83, 'Symptom_2', 'dehydration'), (83, 'Symptom_3', 'diarrhoea'), (84, 'Symptom_1', 'vomiting'), (84, 'Symptom_2', 'sunken_eyes'), (84, 'Symptom_3', 'diarrhoea'), (85, 'Symptom_1', 'vomiting'), (85, 'Symptom_2', 'sunken_eyes'), (85, 'Symptom_3', 'dehydration'), (86, 'Symptom_1', 'vomiting'), (86, 'Symptom_2', 'sunken_eyes'), (86, 'Symptom_3', 'dehydration'), (86, 'Symptom_4', 'diarrhoea'), (87, 'Symptom_1', 'sunken_eyes'), (87, 'Symptom_2', 'dehydration'), (87, 'Symptom_3', 'diarrhoea'), (88, 'Symptom_1', 'vomiting'), (88, 'Symptom_2', 'dehydration'), (88, 'Symptom_3', 'diarrhoea'), (89, 'Symptom_1', 'vomiting'), (89, 'Symptom_2', 'sunken_eyes'), (89, 'Symptom_3', 'diarrhoea'), (90, 'Symptom_1', 'fatigue'), (90, 'Symptom_2', 'cough'), (90, 'Symptom_3', 'high_fever'), (90, 'Symptom_4', 'breathlessness'), (90, 'Symptom_5', 'family_history'), (90, 'Symptom_6', 'mucoid_sputum'), (91, 'Symptom_1', 'cough'), (91, 'Symptom_2', 'high_fever'), (91, 'Symptom_3', 'breathlessness'), (91, 'Symptom_4', 'family_history'), (91, 'Symptom_5', 'mucoid_sputum'), (92, 'Symptom_1', 'fatigue'), (92, 'Symptom_2', 'high_fever'), (92, 'Symptom_3', 'breathlessness'), (92, 'Symptom_4', 'family_history'), (92, 'Symptom_5', 'mucoid_sputum'), (93, 'Symptom_1', 'fatigue'), (93, 'Symptom_2', 'cough'), (93, 'Symptom_3', 'breathlessness'), (93, 'Symptom_4', 'family_history'), (93, 'Symptom_5', 'mucoid_sputum'), (94, 'Symptom_1', 'fatigue'), (94, 'Symptom_2', 'cough'), (94, 'Symptom_3', 'high_fever'), (94, 'Symptom_4', 'family_history'), (94, 'Symptom_5', 'mucoid_sputum'), (95, 'Symptom_1', 'fatigue'), (95, 'Symptom_2', 'cough'), (95, 'Symptom_3', 'high_fever'), (95, 'Symptom_4', 'breathlessness'), (95, 'Symptom_5', 'mucoid_sputum'), (96, 'Symptom_1', 'fatigue'), (96, 'Symptom_2', 'cough'), (96, 'Symptom_3', 'high_fever'), (96, 'Symptom_4', 'breathlessness'), (96, 'Symptom_5', 'family_history'), (97, 'Symptom_1', 'fatigue'), (97, 'Symptom_2', 'cough'), (97, 'Symptom_3', 'high_fever'), (97, 'Symptom_4', 'breathlessness'), (97, 'Symptom_5', 'family_history'), (97, 'Symptom_6', 'mucoid_sputum'), (98, 'Symptom_1', 'cough'), (98, 'Symptom_2', 'high_fever'), (98, 'Symptom_3', 'breathlessness'), (98, 'Symptom_4', 'family_history'), (98, 'Symptom_5', 'mucoid_sputum'), (99, 'Symptom_1', 'fatigue'), (99, 'Symptom_2', 'high_fever'), (99, 'Symptom_3', 'breathlessness'), (99, 'Symptom_4', 'family_history'), (99, 'Symptom_5', 'mucoid_sputum'), (100, 'Symptom_1', 'headache'), (100, 'Symptom_2', 'chest_pain'), (100, 'Symptom_3', 'dizziness'), (100, 'Symptom_4', 'loss_of_balance'), (100, 'Symptom_5', 'lack_of_concentration'), (101, 'Symptom_1', 'chest_pain'), (101, 'Symptom_2', 'dizziness'), (101, 'Symptom_3', 'loss_of_balance'), (101, 'Symptom_4', 'lack_of_concentration'), (102, 'Symptom_1', 'headache'), (102, 'Symptom_2', 'dizziness'), (102, 'Symptom_3', 'loss_of_balance'), (102, 'Symptom_4', 'lack_of_concentration'), (103, 'Symptom_1', 'headache'), (103, 'Symptom_2', 'chest_pain'), (103, 'Symptom_3', 'loss_of_balance'), (103, 'Symptom_4', 'lack_of_concentration'), (104, 'Symptom_1', 'headache'), (104, 'Symptom_2', 'chest_pain'), (104, 'Symptom_3', 'dizziness'), (104, 'Symptom_4', 'lack_of_concentration'), (105, 'Symptom_1', 'headache'), (105, 'Symptom_2', 'chest_pain'), (105, 'Symptom_3', 'dizziness'), (105, 'Symptom_4', 'loss_of_balance'), (106, 'Symptom_1', 'headache'), (106, 'Symptom_2', 'chest_pain'), (106, 'Symptom_3', 'dizziness'), (106, 'Symptom_4', 'loss_of_balance'), (106, 'Symptom_5', 'lack_of_concentration'), (107, 'Symptom_1', 'chest_pain'), (107, 'Symptom_2', 'dizziness'), (107, 'Symptom_3', 'loss_of_balance'), (107, 'Symptom_4', 'lack_of_concentration'), (108, 'Symptom_1', 'headache'), (108, 'Symptom_2', 'dizziness'), (108, 'Symptom_3', 'loss_of_balance'), (108, 'Symptom_4', 'lack_of_concentration'), (109, 'Symptom_1', 'headache'), (109, 'Symptom_2', 'chest_pain'), (109, 'Symptom_3', 'loss_of_balance'), (109, 'Symptom_4', 'lack_of_concentration'), (110, 'Symptom_1', 'acidity'), (110, 'Symptom_2', 'indigestion'), (110, 'Symptom_3', 'headache'), (110, 'Symptom_4', 'blurred_and_distorted_vision'), (110, 'Symptom_5', 'excessive_hunger'), (110, 'Symptom_6', 'stiff_neck'), (110, 'Symptom_7', 'depression'), (110, 'Symptom_8', 'irritability'), (110, 'Symptom_9', 'visual_disturbances'), (111, 'Symptom_1', 'indigestion'), (111, 'Symptom_2', 'headache'), (111, 'Symptom_3', 'blurred_and_distorted_vision'), (111, 'Symptom_4', 'excessive_hunger'), (111, 'Symptom_5', 'stiff_neck'), (111, 'Symptom_6', 'depression'), (111, 'Symptom_7', 'irritability'), (111, 'Symptom_8', 'visual_disturbances'), (112, 'Symptom_1', 'acidity'), (112, 'Symptom_2', 'headache'), (112, 'Symptom_3', 'blurred_and_distorted_vision'), (112, 'Symptom_4', 'excessive_hunger'), (112, 'Symptom_5', 'stiff_neck'), (112, 'Symptom_6', 'depression'), (112, 'Symptom_7', 'irritability'), (112, 'Symptom_8', 'visual_disturbances'), (113, 'Symptom_1', 'acidity'), (113, 'Symptom_2', 'indigestion'), (113, 'Symptom_3', 'blurred_and_distorted_vision'), (113, 'Symptom_4', 'excessive_hunger'), (113, 'Symptom_5', 'stiff_neck'), (113, 'Symptom_6', 'depression'), (113, 'Symptom_7', 'irritability'), (113, 'Symptom_8', 'visual_disturbances'), (114, 'Symptom_1', 'acidity'), (114, 'Symptom_2', 'indigestion'), (114, 'Symptom_3', 'headache'), (114, 'Symptom_4', 'excessive_hunger'), (114, 'Symptom_5', 'stiff_neck'), (114, 'Symptom_6', 'depression'), 

In [6]:
stacked_dataframe = pd.DataFrame(first_list)
stacked_dataframe[3] = 1
display(stacked_dataframe)

          0          1                     2  3
0         0  Symptom_1               itching  1
1         0  Symptom_2             skin_rash  1
2         0  Symptom_3  nodal_skin_eruptions  1
3         0  Symptom_4   dischromic _patches  1
4         1  Symptom_1             skin_rash  1
...     ...        ...                   ... ..
36643  4919  Symptom_1             skin_rash  1
36644  4919  Symptom_2            high_fever  1
36645  4919  Symptom_3               blister  1
36646  4919  Symptom_4  red_sore_around_nose  1
36647  4919  Symptom_5     yellow_crust_ooze  1

[36648 rows x 4 columns]

In [7]:
#This is encoding with 1
indra_chowk = pd.pivot_table(data=stacked_dataframe,index=0,columns=2,values=3)
#This is encoding with 0
indra_chowk = indra_chowk.fillna('0')
indra_chowk = indra_chowk.astype(int)
display(indra_chowk)

2,abdominal_pain,abnormal_menstruation,acidity,acute_liver_failure,altered_sensorium,anxiety,back_pain,belly_pain,blackheads,bladder_discomfort,...,vomiting,watering_from_eyes,weakness_in_limbs,weakness_of_one_body_side,weight_gain,weight_loss,yellow_crust_ooze,yellow_urine,yellowing_of_eyes,yellowish_skin
0,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4916,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4917,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4918,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4919,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [8]:
disease = data_set['Disease']
from sklearn.preprocessing import LabelEncoder
disease_encoder = LabelEncoder()
encoding_disease = disease_encoder.fit_transform(disease)
encoded_disease = pd.Series(encoding_disease)
display(encoded_disease)

0       15
1       15
2       15
3       15
4       15
        ..
4915     0
4916     2
4917    38
4918    35
4919    27
Length: 4920, dtype: int64

In [9]:
import warnings
warnings.filterwarnings('ignore')
indra_chowk.insert(loc=0,column='Disease',value=encoded_disease)
display(indra_chowk)

2,Disease,abdominal_pain,abnormal_menstruation,acidity,acute_liver_failure,altered_sensorium,anxiety,back_pain,belly_pain,blackheads,...,vomiting,watering_from_eyes,weakness_in_limbs,weakness_of_one_body_side,weight_gain,weight_loss,yellow_crust_ooze,yellow_urine,yellowing_of_eyes,yellowish_skin
0,,,,,,,,,,,,,,,,,,,,,
0,15,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,15,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,15,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,15,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,15,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4916,2,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4917,38,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4918,35,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4919,27,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [10]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 8.1 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [11]:
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from catboost import CatBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier

classifier_dictionary = {
    #"Support Vector Machine" : SVC(),
    "K-Nearest Neighbor" : KNeighborsClassifier(),
    "Logistic Regression" : LogisticRegression(),
    "Gaussian Naive Bayes" : GaussianNB(),
    "Multinomial Naive Bayes" : MultinomialNB(),
    "Bernoulli Naive Bayes" : BernoulliNB(),
    "Random Forest" : RandomForestClassifier(),
    "Light Boost" : LGBMClassifier()
}

In [12]:
# Categorizing the symptoms and diseases to train the classifiers
symptom_feature = indra_chowk.drop('Disease',axis=1)
disease_target = indra_chowk['Disease']

In [13]:
for name_of_classifier,classifier in classifier_dictionary.items():
  classifier.fit(symptom_feature,disease_target)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002237 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 262
[LightGBM] [Info] Number of data points in the train set: 4920, number of used features: 131
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Info] Start training from score -3.713572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [14]:
matched_list = [ ]
unmatched_list = [ ]
training_list = list(indra_chowk.columns)
training_list.remove('Disease')
testing_list = list(symbi_predict.columns)
testing_list.remove('prognosis')
for e in testing_list:
  if(e in training_list):
    matched_list.append(e)
  elif(e not in training_list):
    unmatched_list.append(e)
'''print(matched_list)
print(unmatched_list)'''
print(training_list)

['abdominal_pain', 'abnormal_menstruation', 'acidity', 'acute_liver_failure', 'altered_sensorium', 'anxiety', 'back_pain', 'belly_pain', 'blackheads', 'bladder_discomfort', 'blister', 'blood_in_sputum', 'bloody_stool', 'blurred_and_distorted_vision', 'breathlessness', 'brittle_nails', 'bruising', 'burning_micturition', 'chest_pain', 'chills', 'cold_hands_and_feets', 'coma', 'congestion', 'constipation', 'continuous_feel_of_urine', 'continuous_sneezing', 'cough', 'cramps', 'dark_urine', 'dehydration', 'depression', 'diarrhoea', 'dischromic _patches', 'distention_of_abdomen', 'dizziness', 'drying_and_tingling_lips', 'enlarged_thyroid', 'excessive_hunger', 'extra_marital_contacts', 'family_history', 'fast_heart_rate', 'fatigue', 'fluid_overload', 'foul_smell_of urine', 'headache', 'high_fever', 'hip_joint_pain', 'history_of_alcohol_consumption', 'increased_appetite', 'indigestion', 'inflammatory_nails', 'internal_itching', 'irregular_sugar_level', 'irritability', 'irritation_in_anus', 'itching', 'joint_pain', 'knee_pain', 'lack_of_concentration', 'lethargy', 'loss_of_appetite', 'loss_of_balance', 'loss_of_smell', 'malaise', 'mild_fever', 'mood_swings', 'movement_stiffness', 'mucoid_sputum', 'muscle_pain', 'muscle_wasting', 'muscle_weakness', 'nausea', 'neck_pain', 'nodal_skin_eruptions', 'obesity', 'pain_behind_the_eyes', 'pain_during_bowel_movements', 'pain_in_anal_region', 'painful_walking', 'palpitations', 'passage_of_gases', 'patches_in_throat', 'phlegm', 'polyuria', 'prominent_veins_on_calf', 'puffy_face_and_eyes', 'pus_filled_pimples', 'receiving_blood_transfusion', 'receiving_unsterile_injections', 'red_sore_around_nose', 'red_spots_over_body', 'redness_of_eyes', 'restlessness', 'runny_nose', 'rusty_sputum', 'scurring', 'shivering', 'silver_like_dusting', 'sinus_pressure', 'skin_peeling', 'skin_rash', 'slurred_speech', 'small_dents_in_nails', 'spinning_movements', 'spotting_ urination', 'stiff_neck', 'stomach_bleeding', 'stomach_pain', 'sunken_eyes', 'sweating', 'swelled_lymph_nodes', 'swelling_joints', 'swelling_of_stomach', 'swollen_blood_vessels', 'swollen_extremeties', 'swollen_legs', 'throat_irritation', 'toxic_look_(typhos)', 'ulcers_on_tongue', 'unsteadiness', 'visual_disturbances', 'vomiting', 'watering_from_eyes', 'weakness_in_limbs', 'weakness_of_one_body_side', 'weight_gain', 'weight_loss', 'yellow_crust_ooze', 'yellow_urine', 'yellowing_of_eyes', 'yellowish_skin']

In [15]:
#Arranging the order of the columns
wow = symbi_predict[training_list]
display(wow)

,abdominal_pain,abnormal_menstruation,acidity,acute_liver_failure,altered_sensorium,anxiety,back_pain,belly_pain,blackheads,bladder_discomfort,...,vomiting,watering_from_eyes,weakness_in_limbs,weakness_of_one_body_side,weight_gain,weight_loss,yellow_crust_ooze,yellow_urine,yellowing_of_eyes,yellowish_skin
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4956,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4957,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4958,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4959,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4960,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [16]:
disease_rename_map = {
    "Fungal Infection" : "Fungal infection",
    "Chronic Cholestasis" : "Chronic cholestasis",
    "Cervical Spondylosis" : "Cervical spondylosis",
    "Hepatitis A" : "hepatitis A",
    "Alcoholic Hepatitis" : "Alcoholic hepatitis",
    "Heart Attack" : "Heart attack",
    "Varicose Veins" : "Varicose veins",
    "Urinary Tract Infection" : "Urinary tract infection",
    "Chickenpox" : "Chicken pox",
    "Peptic Ulcer Disease" : "Peptic ulcer diseae",
    "Dimorphic Hemmorhoids (piles)" : "Dimorphic hemmorhoids(piles)",
    "Osteoarthritis" : "Osteoarthristis",
    "Vertigo" : "(vertigo) Paroymsal  Positional Vertigo"
}

In [17]:
just_checking = symbi_predict['prognosis']
just_checking = just_checking.replace(disease_rename_map)
display(just_checking)

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...
4956    (vertigo) Paroymsal  Positional Vertigo
4957                                       Acne
4958                    Urinary tract infection
4959                                  Psoriasis
4960                                   Impetigo
Name: prognosis, Length: 4961, dtype: object

In [18]:
encoding_symbi = disease_encoder.transform(just_checking)
encoded_symbi_disease = pd.Series(encoding_symbi)
display(encoded_symbi_disease)

0       15
1       15
2       15
3       15
4       15
        ..
4956     0
4957     2
4958    38
4959    35
4960    27
Length: 4961, dtype: int64

In [19]:
import numpy as np
from sklearn.metrics import accuracy_score
def corrupt(df, flip_frac=0.15, seed=42):
    rng = np.random.default_rng(seed)
    mask = rng.random(df.shape) < flip_frac
    return df ^ mask.astype(int)

X_test_noisy = corrupt(wow)
name_list = [ ]
noisy_list = [ ]
clean_list = [ ]
difference_list = [ ]

for name, model in classifier_dictionary.items():
    name_list.append(name)
    acc_clean = accuracy_score(encoded_symbi_disease, model.predict(wow))
    clean_list.append(acc_clean)
    acc_noisy = accuracy_score(encoded_symbi_disease, model.predict(X_test_noisy))
    noisy_list.append(acc_noisy)
    accuracy_difference = (acc_clean-acc_noisy)
    difference_list.append(accuracy_difference)
comparison_dictionary = {
        "Classifier" : name_list,
        "Noisy symptoms accuracy" : noisy_list,
        "Clean symptoms accuracy" : clean_list,
        "Accuracy difference" : difference_list
    }
ranjana_lipi = pd.DataFrame(comparison_dictionary)
ranjana_lipi = ranjana_lipi.sort_values(by="Accuracy difference",ascending=True)
display(ranjana_lipi)

,Classifier,Noisy symptoms accuracy,Clean symptoms accuracy,Accuracy difference
4,Bernoulli Naive Bayes,0.906470,1.0,0.093530
0,K-Nearest Neighbor,0.904656,1.0,0.095344
1,Logistic Regression,0.896997,1.0,0.103003
2,Gaussian Naive Bayes,0.861117,1.0,0.138883
3,Multinomial Naive Bayes,0.852046,1.0,0.147954
5,Random Forest,0.469663,1.0,0.530337
6,Light Boost,0.434993,1.0,0.565007

In [20]:
from sklearn.metrics import accuracy_score
def corrupt(df,seed=10,flip_frac=0.15):
  rng = np.random.default_rng(seed)
  mask = rng.random(df.shape) < flip_frac
  return df ^ mask.astype(int)



corrupted = corrupt(wow)
name_list = [ ]
clean_accuracy_list = [ ]
corrupted_accuracy_list = [ ]
accuracy_difference_list = [ ]
for classifier_name,classifier in classifier_dictionary.items():
  name_list.append(classifier_name)
  clean_accuracy = accuracy_score(encoded_symbi_disease,classifier.predict(wow))
  clean_accuracy_list.append(clean_accuracy)
  corrupted_accuracy = accuracy_score(encoded_symbi_disease,classifier.predict(corrupted))
  corrupted_accuracy_list.append(corrupted_accuracy)
  accuracy_difference = (clean_accuracy-corrupted_accuracy)
  accuracy_difference_list.append(accuracy_difference)
cutie_antu = {
    "Name of classifier" : name_list,
    "Clean accuracy" : clean_accuracy_list,
    "Corrupted accuracy" : corrupted_accuracy_list,
    "Difference in accuracy" : accuracy_difference_list
}

comparison_dataframe = pd.DataFrame(cutie_antu)
comparison_dataframe = comparison_dataframe.sort_values(by="Difference in accuracy",ascending=True)
print(comparison_dataframe)

        Name of classifier  Clean accuracy  Corrupted accuracy  \
0       K-Nearest Neighbor             1.0            0.899617
4    Bernoulli Naive Bayes             1.0            0.896795
1      Logistic Regression             1.0            0.887926
2     Gaussian Naive Bayes             1.0            0.864947
3  Multinomial Naive Bayes             1.0            0.842370
5            Random Forest             1.0            0.470470
6              Light Boost             1.0            0.425116

   Difference in accuracy
0                0.100383
4                0.103205
1                0.112074
2                0.135053
3                0.157630
5                0.529530
6                0.574884

In [21]:
import numpy as np
import pandas as pd

def corrupt(df, flip_frac=0.15, seed=42):
    rng = np.random.default_rng(seed)
    mask = rng.random(df.shape) < flip_frac
    return df ^ mask.astype(int)

results = []
for frac in [0.02, 0.05, 0.10, 0.15]:
    X_test_noisy = corrupt(wow, flip_frac=frac)
    for name, model in classifier_dictionary.items():
        acc = accuracy_score(encoded_symbi_disease, model.predict(X_test_noisy))
        results.append({"flip_frac": frac, "model": name, "accuracy": round(acc, 4)})

results_df = pd.DataFrame(results)
pivot = results_df.pivot(index="model", columns="flip_frac", values="accuracy")
display(pivot)

flip_frac                  0.02    0.05    0.10    0.15
model
Bernoulli Naive Bayes    0.9998  0.9938  0.9682  0.9065
Gaussian Naive Bayes     0.9996  0.9913  0.9514  0.8611
K-Nearest Neighbor       0.9996  0.9944  0.9688  0.9047
Light Boost              0.9214  0.7986  0.5918  0.4350
Logistic Regression      0.9996  0.9927  0.9645  0.8970
Multinomial Naive Bayes  0.9972  0.9901  0.9641  0.8520
Random Forest            0.9946  0.9403  0.7031  0.4697

In [22]:
import numpy as np
beabadobee = [ ]
def corrupt(df,flip_frac=0.15,seed=42):
  rng = np.random.default_rng(seed)
  mask = rng.random(df.shape) < flip_frac
  return df ^ mask.astype(int)

for fraction in [0.02,0.05,0.10,0.15]:
  abcd = corrupt(wow,flip_frac=fraction)
  for name,machine in classifier_dictionary.items():
    heram_accuracy = accuracy_score(encoded_symbi_disease,machine.predict(abcd))
    beabadobee.append({"Flipped Fraction" : fraction, "Machine" : name, "Actual Accuracy" : round(heram_accuracy,4)})

df_two = pd.DataFrame(beabadobee)
df_three = df_two.pivot(index = "Machine", columns= "Flipped Fraction", values = "Actual Accuracy")
display(df_three)

Flipped Fraction           0.02    0.05    0.10    0.15
Machine
Bernoulli Naive Bayes    0.9998  0.9938  0.9682  0.9065
Gaussian Naive Bayes     0.9996  0.9913  0.9514  0.8611
K-Nearest Neighbor       0.9996  0.9944  0.9688  0.9047
Light Boost              0.9214  0.7986  0.5918  0.4350
Logistic Regression      0.9996  0.9927  0.9645  0.8970
Multinomial Naive Bayes  0.9972  0.9901  0.9641  0.8520
Random Forest            0.9946  0.9403  0.7031  0.4697

In [26]:
knn_object = classifier_dictionary['K-Nearest Neighbor']
import pickle as pkl
with open("test_deployment.pkl","wb") as test_machine:
  pkl.dump(knn_object,test_machine)